repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --check
        language: system
        types: [python]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: uv run flake8 src
        language: system
        types: [python]
        pass_filenames: false

      - id: ty-check
        name: ty check
        entry: uv run ty check
        language: system
        types: [python]
        pass_filenames: false
